"""add_allows_multiple_tags_to_questions

Revision ID: 3aec3f16a4c7
Revises: 9447fdd51cf8
Create Date: 2025-11-21 00:55:49.809750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aec3f16a4c7'
down_revision: Union[str, None] = '9447fdd51cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('questions', sa.Column('allows_multiple_tags', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE questions SET allows_multiple_tags = TRUE WHERE allows_multiple_tags IS NULL")
    # Now make it NOT NULL
    op.alter_column('questions', 'allows_multiple_tags', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'allows_multiple_tags')
    # ### end Alembic commands ###
