"""add_post_study_questions_table

Revision ID: 9447fdd51cf8
Revises: 960a8b229b52
Create Date: 2025-11-21 00:41:20.733672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9447fdd51cf8'
down_revision: Union[str, None] = '960a8b229b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists, if not create it
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'post_study_questions' not in tables:
        # Create table if it doesn't exist
        op.create_table('post_study_questions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('question_id', sa.Integer(), nullable=False),
            sa.Column('study_id', sa.Integer(), nullable=False),
            sa.Column('order', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
            sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('question_id', 'study_id', name='uq_post_study_question')
        )
        op.create_index(op.f('ix_post_study_questions_id'), 'post_study_questions', ['id'], unique=False)
        op.create_index(op.f('ix_post_study_questions_question_id'), 'post_study_questions', ['question_id'], unique=False)
        op.create_index(op.f('ix_post_study_questions_study_id'), 'post_study_questions', ['study_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'post_study_questions' in inspector.get_table_names():
        op.drop_index(op.f('ix_post_study_questions_study_id'), table_name='post_study_questions')
        op.drop_index(op.f('ix_post_study_questions_question_id'), table_name='post_study_questions')
        op.drop_index(op.f('ix_post_study_questions_id'), table_name='post_study_questions')
        op.drop_table('post_study_questions')
    # ### end Alembic commands ###
