"""add_pre_study_questions_table

Revision ID: 960a8b229b52
Revises: 
Create Date: 2025-11-21 00:37:33.227091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960a8b229b52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists, if not create it
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'pre_study_questions' not in tables:
        # Create table if it doesn't exist
        op.create_table('pre_study_questions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('question_id', sa.Integer(), nullable=False),
            sa.Column('study_id', sa.Integer(), nullable=False),
            sa.Column('order', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
            sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('question_id', 'study_id', name='uq_pre_study_question')
        )
        op.create_index(op.f('ix_pre_study_questions_id'), 'pre_study_questions', ['id'], unique=False)
        op.create_index(op.f('ix_pre_study_questions_question_id'), 'pre_study_questions', ['question_id'], unique=False)
        op.create_index(op.f('ix_pre_study_questions_study_id'), 'pre_study_questions', ['study_id'], unique=False)
    else:
        # Table exists, rename order_index to order if it exists
        columns = [col['name'] for col in inspector.get_columns('pre_study_questions')]
        if 'order_index' in columns and 'order' not in columns:
            op.alter_column('pre_study_questions', 'order_index', new_column_name='order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('pre_study_questions')]
    
    if 'order' in columns and 'order_index' not in columns:
        op.alter_column('pre_study_questions', 'order', new_column_name='order_index')
    elif 'pre_study_questions' in inspector.get_table_names():
        op.drop_index(op.f('ix_pre_study_questions_study_id'), table_name='pre_study_questions')
        op.drop_index(op.f('ix_pre_study_questions_question_id'), table_name='pre_study_questions')
        op.drop_index(op.f('ix_pre_study_questions_id'), table_name='pre_study_questions')
        op.drop_table('pre_study_questions')
    # ### end Alembic commands ###
