"""add_is_required_to_pre_and_post_study_questions

Revision ID: 998d7e542684
Revises: 3aec3f16a4c7
Create Date: 2025-11-21 02:02:55.435199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '998d7e542684'
down_revision: Union[str, None] = '3aec3f16a4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pre_response_questions_id', table_name='pre_response_questions')
    op.drop_index('ix_pre_response_questions_question_id', table_name='pre_response_questions')
    op.drop_index('ix_pre_response_questions_train_configuration_id', table_name='pre_response_questions')
    op.drop_table('pre_response_questions')
    # Add column as nullable first
    op.add_column('post_study_questions', sa.Column('is_required', sa.Boolean(), nullable=True))
    op.add_column('pre_study_questions', sa.Column('is_required', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE post_study_questions SET is_required = FALSE WHERE is_required IS NULL")
    op.execute("UPDATE pre_study_questions SET is_required = FALSE WHERE is_required IS NULL")
    # Make column non-nullable
    op.alter_column('post_study_questions', 'is_required', nullable=False, server_default='false')
    op.alter_column('pre_study_questions', 'is_required', nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pre_study_questions', 'is_required')
    op.drop_column('post_study_questions', 'is_required')
    op.create_table('pre_response_questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('train_configuration_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('free_text_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='pre_response_questions_question_id_fkey'),
    sa.ForeignKeyConstraint(['train_configuration_id'], ['train_configurations.id'], name='pre_response_questions_train_configuration_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pre_response_questions_pkey'),
    sa.UniqueConstraint('question_id', 'train_configuration_id', name='uq_pre_response_question')
    )
    op.create_index('ix_pre_response_questions_train_configuration_id', 'pre_response_questions', ['train_configuration_id'], unique=False)
    op.create_index('ix_pre_response_questions_question_id', 'pre_response_questions', ['question_id'], unique=False)
    op.create_index('ix_pre_response_questions_id', 'pre_response_questions', ['id'], unique=False)
    # ### end Alembic commands ###
